### ISSUE TITLE
Write nginx.conf file to configurable location

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/php-nginx#10]
## Blocked
This issue is blocked from completion by the release of https://github.com/paketo-buildpacks/nginx/pull/373

## Context
In #3, the `nginx.conf` file was hardcoded to be written to `/workspace`, since Go templating via the Nginx buildpack was only performed in this location.

## Issue
Once https://github.com/paketo-buildpacks/nginx/issues/358 is implemented and released, we can write the configuration file to the PHP Nginx layer and set the `BP_NGINX_CONF_LOCATION` env. var that the Nginx buildpack will be able to consume.

## Outcome
The PHP Nginx buildpack writes it's configuration file to the PHP Nginx buildpack layer, and makes it discoverable via `BP_NGINX_CONF_LOCATION` such that in a build (such as the one in the [default test](https://github.com/paketo-buildpacks/php-nginx/blob/main/integration/default_test.go)) with the NGINX buildpack the build succeeds and the app is queryable.

**Comment by ForestEckhardt** [comment]
Is this issue resolved by https://github.com/paketo-buildpacks/nginx/pull/373

**Comment by TisVictress** [comment]
> Is this issue resolved by [paketo-buildpacks/nginx#373](https://github.com/paketo-buildpacks/nginx/pull/373)

@ForestEckhardt It doesn't resolve this issue but it does unblock it. Hilariously, I cannot remove the blocked label.

**Comment by sophiewigmore** [comment]
@TisVictress can you please add context as to why you drafted?

**Comment by TisVictress** [comment]
After some discussion, we decided to put this down for now so the PR referenced here has been drafted. In order to get this working, we needed to make the php-nginx layer available in the build phase to subsequent buildpacks, which caused us to re-evaluate if this is worth it. This discussion also brought up the following concerns:
* Do we want this environment variable to be a user-facing variable (since in this case, we are setting this within the php-nginx buildpack)? Should it be given a different name with the `BP_` prefix?
* Should we be using a user-focused environment variable (that starts with the prefix `BP_`) to configure another buildpack within this buildpack? Forest suggested that at some point it might be good to have a formal API for namespacing environment variables or inter-buildpack communication. 
* Things could potentially break if the user decides to manually set `BP_NGINX_CONF_LOCATION` in addition to it being set by the php-nginx buildpack

**Comment by robdimsdale** [comment]
I think these are great points @TisVictress.

I agree that the proposed interface is brittle, as by relying on the `BP_NGINX_CONF_LOCATION` we run the risk of clashing with a user who is also providing this.

I agree that it would be great to have a more formal interface for inter-buildpack communication that doesn't rely on the same system that users use to configure (i.e. `BP_` environment variables). I don't have any well-formed ideas on this yet, though.

The risk of not making progress on this feature - that we are potentially overwriting a user-provided `nginx.conf` under `/workspace` - is probably about the same risk as implementing it in its current form - that a user will overwrite our config via `BP_NGINX_CONF_LOCATION`.

So, I think it's fine to put this issue down while we evaluate what a more formal inter-buildpack communication path might look like.
